#Day 2: "30 Days of python programming"
first_name = 'Martin'
last_name = 'Emanuel'
full_name = 'Martin Emanuel Perez Almaguer'
country = 'AGS'
city = 'Ags'
age = '18 years'
year = '2025'
is_married = 'false'
is_true = 'true'
is_ligh_on = 'true'
first_name, last_name, country, city = 'Martin', 'Emanuel' , 'AGS', 'Ags'
