#Exercise level 2
print(5+5) #addition(+)
print(8-2) #subtraction(-)
print(9*9) #multiplication(*)
print(80%10) #modulus(%)
print(80/2)  #division(/)
print(9**8)  #exponential(**)
print(40//2) #floor division operator(//)
print(input('Your family name'))
print('Martin')
print('victoria')
print('elizabeth')
print('brayan')
print(input('Enter your country'))
print('Aguascalientes')
print('I am enjoying 30 days of python')
print(type(10))
print(type (9.8))
print(type (3.14))
print(type (4-4j))
print(type('Asabeneth','Python','finland'))
print(type ('Martin'))
print(type ('Victoria','Brayan','LIliana'))
print(type ('Aguascalientes'))

#Exercise level 3
#1)
print(3)
print(7,8)
print(1+g)
print("I love my pets")
print(true)
print(type(['It','He','She']))
print('scrapy','hanzo','bruce')
print(4,3,2)

#2)

print('distancia eclaudiana')
p1= (2,3)
p2= (7,9)
suma_de_cuadrados_=((p2[0])**2)+((p2[1]-p1)**2)
distancia= (suma_de_cuadrados_)**0.5
print('la distancia eclaudiana de los puntos',p1, 'y',p2,round(distancia,2))

